#!/bin/bash

#SBATCH --job-name=cn12_test # Job name
#SBATCH --output=cn12_test.out
#SBATCH --cpus-per-task=1                               
#SBATCH --exclude=cn[3-11,13-19]
#SBATCH --exclude=desktop[1-16]
#SBATCH --time=00:05:00
#SBATCH --nodelist=cn12
#SBATCH --gres=gpu:rtx8000:2
#SBATCH --time=00:05:00                               
#SBATCH --partition=cn12quadro

module load OpenMPI/4.1.5-GCC-12.3.0
module load CUDA/12.1.1
module load OpenBLAS/0.3.23-GCC-12.3.0
module load ScaLAPACK/2.2.0-gompi-2023a-fb
echo "Running on $(hostname):"

nvidia-smi 
